#!bin/bash

# Move code
sudo mkdir /usr/share/BareShare
sudo cp bareshare.py /usr/share/BareShare
sudo cp -R icons/ /usr/share/BareShare
sudo cp -R template/ /usr/share/BareShare

# Install the desktop launcher
sudo mv bareshare.desktop /usr/share/applications
cd /usr/share/applications
sudo chmod 644 bareshare.desktop
sudo chown root:root bareshare.desktop
# Add it to unity
